name: skib
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - click=8.2.1
  - exceptiongroup=1.2.0
  - fastapi=0.112.2
  - h11=0.16.0
  - idna=3.7
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.5.0
  - pip=25.1
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - python=3.10.16
  - python-dotenv=1.1.0
  - readline=8.2
  - setuptools=78.1.1
  - sniffio=1.3.0
  - sqlite=3.45.3
  - starlette=0.38.2
  - tk=8.6.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025b
  - uvicorn=0.34.2
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
