name: skib
channels:
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.7.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - colorama=0.4.6
  - distro=1.9.0
  - dnspython=2.7.0
  - exceptiongroup=1.2.0
  - fastapi=0.112.2
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.7
  - iniconfig=2.0.0
  - jinja2=3.1.6
  - jiter=0.10.0
  - lcms2=2.17
  - lerc=4.0.0
  - libcxx=20.1.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=3.0.3
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.45.2
  - libtiff=4.7.0
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.4.2
  - openai=1.82.1
  - openjpeg=2.5.3
  - openssl=3.5.0
  - pip=25.1
  - pluggy=1.6.0
  - pthread-stubs=0.3
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.19.1
  - pymongo=4.11
  - pysocks=1.7.1
  - pytest=8.4.0
  - python=3.10.13
  - python-dotenv=1.1.0
  - python_abi=3.10
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=78.1.1
  - sniffio=1.3.0
  - sqlite=3.45.2
  - starlette=0.38.2
  - tk=8.6.13
  - tomli=2.2.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - uvicorn=0.34.2
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - anthropic==0.54.0
      - asgiref==3.8.1
      - async-timeout==4.0.3
      - attrs==25.3.0
      - authlib==1.3.1
      - autoflake==2.3.1
      - backoff==2.2.1
      - bcrypt==4.3.0
      - beautifulsoup4==4.13.4
      - black==25.1.0
      - build==1.2.2.post1
      - cachetools==5.5.2
      - cffi==1.17.1
      - cfgv==3.4.0
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - chroma-hnswlib==0.7.6
      - chromadb==0.5.18
      - click==8.1.8
      - coloredlogs==15.0.1
      - colorlog==6.9.0
      - cryptography==45.0.3
      - deepl==1.22.0
      - deprecation==2.1.0
      - dill==0.4.0
      - distlib==0.3.9
      - docling==2.36.0
      - docling-core==2.33.0
      - docling-ibm-models==3.4.4
      - docling-parse==4.0.1
      - durationpy==0.10
      - easyocr==1.7.2
      - et-xmlfile==2.0.0
      - feedparser==6.0.11
      - filelock==3.18.0
      - filetype==1.2.0
      - flake8==7.2.0
      - flatbuffers==25.2.10
      - fsspec==2025.5.1
      - google-ai-generativelanguage==0.6.10
      - google-api-core==2.25.1
      - google-api-python-client==2.173.0
      - google-auth==2.40.3
      - google-auth-httplib2==0.2.0
      - google-generativeai==0.8.3
      - googleapis-common-protos==1.70.0
      - grpcio==1.71.0
      - grpcio-health-checking==1.71.0
      - grpcio-status==1.71.0
      - grpcio-tools==1.71.0
      - hf-xet==1.1.2
      - httplib2==0.22.0
      - httptools==0.6.4
      - huggingface-hub==0.32.3
      - humanfriendly==10.0
      - identify==2.6.12
      - imageio==2.37.0
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - isort==6.0.1
      - joblib==1.5.1
      - jsonlines==3.1.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - kiwipiepy==0.21.0
      - kiwipiepy-model==0.21.0
      - kubernetes==33.1.0
      - langchain==0.3.25
      - langchain-chroma==0.2.0
      - langchain-core==0.3.65
      - langchain-openai==0.3.22
      - langchain-teddynote==0.3.45
      - langchain-text-splitters==0.3.8
      - langgraph==0.4.8
      - langgraph-checkpoint==2.1.0
      - langgraph-prebuilt==0.2.2
      - langgraph-sdk==0.1.70
      - langsmith==0.3.45
      - latex2mathml==3.78.0
      - lazy-loader==0.4
      - lxml==5.4.0
      - lz4==4.4.4
      - markdown-it-py==3.0.0
      - marko==2.1.3
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mmh3==4.1.0
      - mpire==2.10.2
      - multiprocess==0.70.18
      - mypy-extensions==1.1.0
      - ninja==1.11.1.4
      - nltk==3.9.1
      - nodeenv==1.9.1
      - numpy==1.26.4
      - oauthlib==3.3.0
      - olefile==0.47
      - onnxruntime==1.22.0
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - opentelemetry-api==1.34.1
      - opentelemetry-exporter-otlp-proto-common==1.34.1
      - opentelemetry-exporter-otlp-proto-grpc==1.34.1
      - opentelemetry-instrumentation==0.55b1
      - opentelemetry-instrumentation-asgi==0.55b1
      - opentelemetry-instrumentation-fastapi==0.55b1
      - opentelemetry-proto==1.34.1
      - opentelemetry-sdk==1.34.1
      - opentelemetry-semantic-conventions==0.55b1
      - opentelemetry-util-http==0.55b1
      - orjson==3.10.18
      - ormsgpack==1.10.0
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pathspec==0.12.1
      - pdf2image==1.17.0
      - pdfminer-six==20250506
      - pdfplumber==0.11.7
      - pillow==11.2.1
      - pinecone-client==6.0.0
      - pinecone-plugin-interface==0.0.7
      - pinecone-text==0.10.0
      - platformdirs==4.3.8
      - posthog==5.0.0
      - pre-commit==4.2.0
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - protoc-gen-openapiv2==0.0.1
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyclipper==1.3.0.post6
      - pycodestyle==2.13.0
      - pycparser==2.22
      - pydantic-settings==2.9.1
      - pyflakes==3.3.2
      - pylatexenc==2.10
      - pymupdf==1.26.0
      - pyparsing==3.2.3
      - pypdfium2==4.30.1
      - pypika==0.48.9
      - pyproject-hooks==1.2.0
      - pytest-asyncio==1.0.0
      - python-bidi==0.6.6
      - python-dateutil==2.9.0.post0
      - python-docx==1.1.2
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - pytz==2025.2
      - rank-bm25==0.2.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rpds-py==0.25.1
      - rsa==4.9.1
      - rtree==1.4.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - semchunk==2.2.2
      - sentence-transformers==4.1.0
      - sgmllib3k==1.0.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - six==1.17.0
      - soupsieve==2.7
      - sqlalchemy==2.0.41
      - sympy==1.14.0
      - tabulate==0.9.0
      - tavily-python==0.7.7
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torch==2.7.0
      - torchvision==0.22.0
      - transformers==4.52.4
      - typer==0.15.4
      - types-requests==2.32.4.20250611
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.4.0
      - uvloop==0.21.0
      - validators==0.34.0
      - virtualenv==20.31.2
      - watchfiles==1.1.0
      - weaviate-client==4.14.4
      - websocket-client==1.8.0
      - websockets==15.0.1
      - wrapt==1.17.2
      - xlsxwriter==3.2.3
      - xxhash==3.5.0
      - zipp==3.23.0
      - zstandard==0.23.0
