name: skib
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.7.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - certifi=2025.4.26
  - colorama=0.4.6
  - distro=1.9.0
  - dnspython=2.7.0
  - exceptiongroup=1.2.0
  - fastapi=0.112.2
  - freetype=2.13.3
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - idna=3.7
  - iniconfig=2.0.0
  - jinja2=3.1.6
  - jiter=0.10.0
  - lcms2=2.17
  - lerc=4.0.0
  - libcxx=20.1.6
  - libdeflate=1.22
  - libffi=3.4.4
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=3.0.3
  - libopenblas=0.3.29
  - libpng=1.6.47
  - libsqlite=3.45.2
  - libtiff=4.7.0
  - libwebp=1.5.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.4.2
  - numpy-base=2.0.1
  - openai=1.82.1
  - openjpeg=2.5.3
  - openssl=3.5.0
  - pip=25.1
  - pluggy=1.6.0
  - pthread-stubs=0.3
  - pydantic=2.10.3
  - pydantic-core=2.27.1
  - pygments=2.19.1
  - pymongo=4.11
  - pysocks=1.7.1
  - pytest=8.4.0
  - python=3.10.13
  - python-dotenv=1.1.0
  - python_abi=3.10
  - pytorch=2.5.1
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - setuptools=78.1.1
  - sniffio=1.3.0
  - sqlite=3.45.2
  - starlette=0.38.2
  - tk=8.6.13
  - tomli=2.2.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - uvicorn=0.34.2
  - wheel=0.45.1
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - async-timeout==4.0.3
      - attrs==25.3.0
      - authlib==1.3.1
      - beautifulsoup4==4.13.4
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.2
      - click==8.1.8
      - colorlog==6.9.0
      - cryptography==45.0.3
      - deprecation==2.1.0
      - dill==0.4.0
      - docling==2.36.0
      - docling-core==2.33.0
      - docling-ibm-models==3.4.4
      - docling-parse==4.0.1
      - easyocr==1.7.2
      - et-xmlfile==2.0.0
      - filelock==3.18.0
      - filetype==1.2.0
      - fsspec==2025.5.1
      - grpcio==1.71.0
      - grpcio-health-checking==1.71.0
      - grpcio-tools==1.71.0
      - hf-xet==1.1.2
      - huggingface-hub==0.32.3
      - imageio==2.37.0
      - joblib==1.5.1
      - jsonlines==3.1.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonref==1.1.0
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - langchain==0.3.25
      - langchain-core==0.3.65
      - langchain-openai==0.3.22
      - langchain-text-splitters==0.3.8
      - langsmith==0.3.45
      - latex2mathml==3.78.0
      - lazy-loader==0.4
      - lxml==5.4.0
      - markdown-it-py==3.0.0
      - marko==2.1.3
      - mdurl==0.1.2
      - mpire==2.10.2
      - multiprocess==0.70.18
      - ninja==1.11.1.4
      - numpy==2.2.6
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - orjson==3.10.18
      - packaging==24.2
      - pandas==2.2.3
      - pdfminer-six==20250506
      - pdfplumber==0.11.7
      - pillow==11.2.1
      - protobuf==5.29.5
      - pyclipper==1.3.0.post6
      - pycparser==2.22
      - pydantic-settings==2.9.1
      - pylatexenc==2.10
      - pymupdf==1.26.0
      - pypdfium2==4.30.1
      - pytest-asyncio==1.0.0
      - python-bidi==0.6.6
      - python-dateutil==2.9.0.post0
      - python-docx==1.1.2
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - pytz==2025.2
      - referencing==0.36.2
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - rich==14.0.0
      - rpds-py==0.25.1
      - rtree==1.4.0
      - safetensors==0.5.3
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - semchunk==2.2.2
      - sentence-transformers==4.1.0
      - shapely==2.1.1
      - shellingham==1.5.4
      - six==1.17.0
      - soupsieve==2.7
      - sqlalchemy==2.0.41
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - tiktoken==0.9.0
      - tokenizers==0.21.1
      - torchvision==0.22.0
      - transformers==4.52.4
      - typer==0.15.4
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - urllib3==2.4.0
      - validators==0.34.0
      - weaviate-client==4.14.4
      - xlsxwriter==3.2.3
      - zstandard==0.23.0
