version: 1
disable_existing_loggers: False

formatters:
  color:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s%(levelname)-8s%(reset)s | %(asctime)s | %(name)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    log_colors:
      DEBUG:    cyan
      INFO:     green
      WARNING:  yellow
      ERROR:    red
      CRITICAL: bold_red

handlers:
  console:
    class: logging.StreamHandler
    formatter: color
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [console]
    level: INFO
    propagate: False

  fastapi:
    handlers: [console]
    level: INFO
    propagate: False

root:
  handlers: [console]
  level: INFO
