apiVersion: apps/v1
kind: Deployment
metadata:
  name: sk-team-09-ai
  namespace: sk-team-09
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sk-team-09-ai
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8001"
        prometheus.io/path: "/actuator/prometheus"
      labels:
        app: sk-team-09-ai
    spec:
      serviceAccountName: default
      imagePullSecrets:
        - name: amdp-registry
      containers:
        - name: sk-team-09-ai
          image: amdp-registry.skala-ai.com/skala25a/sk-team-09-ai:1.0.0-64-074f48460e5a
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: open-ai-secret
                  key: OPENAI_API_KEY
            - name: AGENT_SUBJECTIVE_GRADER_MODEL
              valueFrom:
                secretKeyRef:
                  name: agent-model-secret
                  key: AGENT_SUBJECTIVE_GRADER_MODEL
            - name: CHROMADB_URL
              valueFrom:
                secretKeyRef:
                  name: chromadb-secret
                  key: CHROMADB_URL
            - name: CHROMADB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: chromadb-secret
                  key: CHROMADB_USERNAME
            - name: CHROMADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: chromadb-secret
                  key: CHROMADB_PASSWORD
            - name: USE_REMOTE_CHROMADB
              valueFrom:
                secretKeyRef:
                  name: chromadb-secret
                  key: USE_REMOTE_CHROMADB
            - name: EMBEDDING_MODEL
              valueFrom:
                secretKeyRef:
                  name: chromadb-secret
                  key: EMBEDDING_MODEL
            - name: LANGSMITH_TRACING
              valueFrom:
                secretKeyRef:
                  name: langsmith-secret
                  key: LANGSMITH_TRACING
            - name: LANGSMITH_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: langsmith-secret
                  key: LANGSMITH_ENDPOINT
            - name: LANGSMITH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: langsmith-secret
                  key: LANGSMITH_API_KEY
            - name: LANGSMITH_PROJECT
              valueFrom:
                secretKeyRef:
                  name: langsmith-secret
                  key: LANGSMITH_PROJECT
            - name: GEMINI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-secret
                  key: GEMINI_API_KEY

          volumeMounts:
            - name: document-volume
              mountPath: /data
      volumes:
        - name: document-volume
          persistentVolumeClaim:
            claimName: skib-documents-ai-pvc
