apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skib-documents-pvc
  namespace: sk-team-09
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
