apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skib-documents-ai-pvc
  namespace: sk-team-09
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-sc-shared
