name: CI/CD AI Image Build and Update YAMLs

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      IMAGE_REGISTRY: docker.io/yoonalim2003
      IMAGE_NAME: sk-team-09-ai
      IMAGE_TAG_BASE: 1.0.0
      GIT_USER_NAME: yoonali
      GIT_USER_EMAIL: yoonalim2003@gmail.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate FINAL_IMAGE_TAG
        id: image_tag
        run: |
          HASH=$(date +%s%N | sha256sum | cut -c1-12)
          FINAL_TAG="${{ env.IMAGE_TAG_BASE }}-${GITHUB_RUN_NUMBER}-${HASH}"
          echo "FINAL_IMAGE_TAG=$FINAL_TAG" >> $GITHUB_ENV
          echo "Final tag: $FINAL_TAG"

      - name: Login to Container Registry
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/amd64 -t $IMAGE_REGISTRY/$IMAGE_NAME:$FINAL_IMAGE_TAG .
          docker push $IMAGE_REGISTRY/$IMAGE_NAME:$FINAL_IMAGE_TAG

      - name: Update YAML files with new image tag
        run: |
          IMAGE_LINE="          image: $IMAGE_REGISTRY/$IMAGE_NAME:$FINAL_IMAGE_TAG"
          for FILE in deploy.yaml document-deploy.yaml test-deploy.yaml; do
            sed -i "s|^[[:space:]]*image:.*\$|$IMAGE_LINE|g" ./k8s/$FILE
          done
          echo "Updated YAMLs:"
          cat ./k8s/deploy.yaml

      - name: Commit and Push updated YAML files
        run: |
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"
          git add ./k8s/deploy.yaml ./k8s/document-deploy.yaml ./k8s/test-deploy.yaml || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "[AUTO] Update deployment images with image $FINAL_IMAGE_TAG"
            git pull --rebase origin main 
            git push
          fi

      - name: Set up latest kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          for FILE in deploy.yaml document-deploy.yaml test-deploy.yaml; do
            kubectl apply -f ./k8s/$FILE -n sk-team-09 
          done
